//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoCMS.Web.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoCMS.Web.Contract.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно прав для просмотра аналитики. Получите подходящий ключ доступа..
        /// </summary>
        public static string Analytics_Forbidden {
            get {
                return ResourceManager.GetString("Analytics_Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурс аналитики не найден..
        /// </summary>
        public static string Analytics_NotFound {
            get {
                return ResourceManager.GetString("Analytics_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только буквы.
        /// </summary>
        public static string Validation_Letters {
            get {
                return ResourceManager.GetString("Validation_Letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только буквы, цифры и символ почеркивания.
        /// </summary>
        public static string Validation_LettersNumbersUnderscore {
            get {
                return ResourceManager.GetString("Validation_LettersNumbersUnderscore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только буквы, цифры, символ почеркивания и дефис.
        /// </summary>
        public static string Validation_LettersNumbersUnderscoreDash {
            get {
                return ResourceManager.GetString("Validation_LettersNumbersUnderscoreDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только буквы и цифры.
        /// </summary>
        public static string Validation_LettersOrNumbers {
            get {
                return ResourceManager.GetString("Validation_LettersOrNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите телефон или email.
        /// </summary>
        public static string Validation_MessageContactRequired {
            get {
                return ResourceManager.GetString("Validation_MessageContactRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите имя.
        /// </summary>
        public static string Validation_NameRequired {
            get {
                return ResourceManager.GetString("Validation_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите телефон.
        /// </summary>
        public static string Validation_PhoneRequired {
            get {
                return ResourceManager.GetString("Validation_PhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Validation_Reqiured {
            get {
                return ResourceManager.GetString("Validation_Reqiured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат email-адреса.
        /// </summary>
        public static string Validation_WrongEmail {
            get {
                return ResourceManager.GetString("Validation_WrongEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только целые положительные числа.
        /// </summary>
        public static string Validation_WrongNumber {
            get {
                return ResourceManager.GetString("Validation_WrongNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неправильный формат адреса.
        /// </summary>
        public static string Validation_WrongURL {
            get {
                return ResourceManager.GetString("Validation_WrongURL", resourceCulture);
            }
        }
    }
}
