//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoCMS.SupportTickets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int MessageId { get; set; }
        public int AuthorId { get; set; }
        public int TicketId { get; set; }
        public string Text { get; set; }
        public bool IsRead { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Ticket Ticket { get; set; }
    }
}
