//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoCMS.SupportTickets.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public Ticket()
        {
            this.Messages = new HashSet<Message>();
        }
    
        public int TicketId { get; set; }
        public string Subject { get; set; }
        public int AuthorId { get; set; }
        public string TicketType { get; set; }
        public bool Resolved { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual ICollection<Message> Messages { get; set; }
    }
}
