//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShopStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShopStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoCMS.Shop.Web.Resources.ShopStrings", typeof(ShopStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Интернет-магазин.
        /// </summary>
        public static string AdminMenu_InternetShop {
            get {
                return ResourceManager.GetString("AdminMenu_InternetShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акции.
        /// </summary>
        public static string AdminMenu_Shop_Actions {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории товаров.
        /// </summary>
        public static string AdminMenu_Shop_Categories {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клиенты.
        /// </summary>
        public static string AdminMenu_Shop_Clients {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наборы товаров.
        /// </summary>
        public static string AdminMenu_Shop_CompatibleGoods {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_CompatibleGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        public static string AdminMenu_Shop_Goods {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производители.
        /// </summary>
        public static string AdminMenu_Shop_Manufacturers {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заказы.
        /// </summary>
        public static string AdminMenu_Shop_Orders {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упаковки.
        /// </summary>
        public static string AdminMenu_Shop_Packs {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Packs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отзывы о товарах.
        /// </summary>
        public static string AdminMenu_Shop_Reviews {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Характеристики товаров.
        /// </summary>
        public static string AdminMenu_Shop_Specs {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_Specs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспорт в Яндекс-Маркет.
        /// </summary>
        public static string AdminMenu_Shop_YmlExport {
            get {
                return ResourceManager.GetString("AdminMenu_Shop_YmlExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string Menu_AcceptMenu {
            get {
                return ResourceManager.GetString("Menu_AcceptMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать меню.
        /// </summary>
        public static string Menu_CreateMenu {
            get {
                return ResourceManager.GetString("Menu_CreateMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Menu_DeleteMenu {
            get {
                return ResourceManager.GetString("Menu_DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вниз.
        /// </summary>
        public static string Menu_Down {
            get {
                return ResourceManager.GetString("Menu_Down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Menu_EditMenu {
            get {
                return ResourceManager.GetString("Menu_EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вверх.
        /// </summary>
        public static string Menu_Up {
            get {
                return ResourceManager.GetString("Menu_Up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картой.
        /// </summary>
        public static string PaymentType_Card {
            get {
                return ResourceManager.GetString("PaymentType_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Наличными.
        /// </summary>
        public static string PaymentType_Cash {
            get {
                return ResourceManager.GetString("PaymentType_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Картой курьеру.
        /// </summary>
        public static string PaymentType_CourierCard {
            get {
                return ResourceManager.GetString("PaymentType_CourierCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курьер.
        /// </summary>
        public static string ShipmentType_Courier {
            get {
                return ResourceManager.GetString("ShipmentType_Courier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string ShipmentType_Post {
            get {
                return ResourceManager.GetString("ShipmentType_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Самовывоз.
        /// </summary>
        public static string ShipmentType_SelfPickup {
            get {
                return ResourceManager.GetString("ShipmentType_SelfPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категории в акции.
        /// </summary>
        public static string Shop_Action_Categories {
            get {
                return ResourceManager.GetString("Shop_Action_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать акцию.
        /// </summary>
        public static string Shop_Action_Create {
            get {
                return ResourceManager.GetString("Shop_Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить акцию.
        /// </summary>
        public static string Shop_Action_Delete {
            get {
                return ResourceManager.GetString("Shop_Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Shop_Action_Description {
            get {
                return ResourceManager.GetString("Shop_Action_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Shop_Action_Discount {
            get {
                return ResourceManager.GetString("Shop_Action_Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать акцию.
        /// </summary>
        public static string Shop_Action_Edit {
            get {
                return ResourceManager.GetString("Shop_Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string Shop_Action_EndDate {
            get {
                return ResourceManager.GetString("Shop_Action_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары в акции.
        /// </summary>
        public static string Shop_Action_Goods {
            get {
                return ResourceManager.GetString("Shop_Action_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Производители в акции.
        /// </summary>
        public static string Shop_Action_Manufacturers {
            get {
                return ResourceManager.GetString("Shop_Action_Manufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Shop_Action_Name {
            get {
                return ResourceManager.GetString("Shop_Action_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить подкатегорию.
        /// </summary>
        public static string Shop_Category_AddSubCategory {
            get {
                return ResourceManager.GetString("Shop_Category_AddSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить категорию.
        /// </summary>
        public static string Shop_Category_CreateCategory {
            get {
                return ResourceManager.GetString("Shop_Category_CreateCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить категорию.
        /// </summary>
        public static string Shop_Category_DeleteCategory {
            get {
                return ResourceManager.GetString("Shop_Category_DeleteCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать категорию.
        /// </summary>
        public static string Shop_Category_EditCategory {
            get {
                return ResourceManager.GetString("Shop_Category_EditCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string Shop_Create {
            get {
                return ResourceManager.GetString("Shop_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Shop_Delete {
            get {
                return ResourceManager.GetString("Shop_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string Shop_Edit {
            get {
                return ResourceManager.GetString("Shop_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запустить экспорт.
        /// </summary>
        public static string Shop_GenerateYmlFile {
            get {
                return ResourceManager.GetString("Shop_GenerateYmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить производителя.
        /// </summary>
        public static string Shop_Manufacturer_Create {
            get {
                return ResourceManager.GetString("Shop_Manufacturer_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить производителя.
        /// </summary>
        public static string Shop_Manufacturer_Delete {
            get {
                return ResourceManager.GetString("Shop_Manufacturer_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать производителя.
        /// </summary>
        public static string Shop_Manufacturer_Edit {
            get {
                return ResourceManager.GetString("Shop_Manufacturer_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить характеристику.
        /// </summary>
        public static string Shop_Spec_Create {
            get {
                return ResourceManager.GetString("Shop_Spec_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить характеристику.
        /// </summary>
        public static string Shop_Spec_Delete {
            get {
                return ResourceManager.GetString("Shop_Spec_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать характеристику.
        /// </summary>
        public static string Shop_Spec_Edit {
            get {
                return ResourceManager.GetString("Shop_Spec_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Артикул.
        /// </summary>
        public static string SortCriterion_Article {
            get {
                return ResourceManager.GetString("SortCriterion_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новизна (сначала постарше).
        /// </summary>
        public static string SortCriterion_CreationDateAsc {
            get {
                return ResourceManager.GetString("SortCriterion_CreationDateAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новизна (сначала новинки).
        /// </summary>
        public static string SortCriterion_CreationDateDesc {
            get {
                return ResourceManager.GetString("SortCriterion_CreationDateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена (сначала подешевле).
        /// </summary>
        public static string SortCriterion_PriceAsc {
            get {
                return ResourceManager.GetString("SortCriterion_PriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена (сначала подороже).
        /// </summary>
        public static string SortCriterion_PriceDesc {
            get {
                return ResourceManager.GetString("SortCriterion_PriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг (сначала непопулярные).
        /// </summary>
        public static string SortCriterion_RatingAsc {
            get {
                return ResourceManager.GetString("SortCriterion_RatingAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг (сначала популярные).
        /// </summary>
        public static string SortCriterion_RatingDesc {
            get {
                return ResourceManager.GetString("SortCriterion_RatingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Релевантность.
        /// </summary>
        public static string SortCriterion_Relevance {
            get {
                return ResourceManager.GetString("SortCriterion_Relevance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспортировать базу в Яндекс-маркет.
        /// </summary>
        public static string YmlExport_Header {
            get {
                return ResourceManager.GetString("YmlExport_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to История экспорта.
        /// </summary>
        public static string YmlExport_History {
            get {
                return ResourceManager.GetString("YmlExport_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата окончания.
        /// </summary>
        public static string YmlExport_History_EndDate {
            get {
                return ResourceManager.GetString("YmlExport_History_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код ошибки.
        /// </summary>
        public static string YmlExport_History_ErrorCode {
            get {
                return ResourceManager.GetString("YmlExport_History_ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата запуска.
        /// </summary>
        public static string YmlExport_History_StartDate {
            get {
                return ResourceManager.GetString("YmlExport_History_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Статус.
        /// </summary>
        public static string YmlExport_History_Status {
            get {
                return ResourceManager.GetString("YmlExport_History_Status", resourceCulture);
            }
        }
    }
}
