CREATE TABLE [dbo].[OptionKey]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Name] NVARCHAR(200) NOT NULL, 
    [CreationDate] DATETIME NOT NULL DEFAULT GETUTCDATE() ,
    [Moderated] BIT NOT NULL DEFAULT 0
)
