CREATE TABLE [Shop].[CartItem]
(
	[CartItemId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CreationDate] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[CartId] UNIQUEIDENTIFIER NOT NULL,
	[GoodsId] INT NOT NULL,
	[PackId] INT NULL,
	[Quantity] INT NOT NULL DEFAULT 1, 
    CONSTRAINT [FK_CartItem_Cart] FOREIGN KEY ([CartId]) REFERENCES [Shop].[Cart]([CartId]) ON DELETE CASCADE, 
    CONSTRAINT [FK_CartItem_Goods] FOREIGN KEY ([GoodsId]) REFERENCES [Shop].[GoodsItem]([GoodsId]) ON DELETE CASCADE, 
    CONSTRAINT [FK_CartItem_Pack] FOREIGN KEY ([PackId]) REFERENCES [Shop].[Pack]([PackId])
)
