CREATE TABLE [Shop].[CompatibleSet]
(
	[CompatibleSetId] INT NOT NULL PRIMARY KEY IDENTITY, 
	[CreationDate] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [Guid]        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() UNIQUE,
    [Name] NVARCHAR(50) NOT NULL
)
