CREATE TABLE [Shop].[Dimension]
(
	[DimensionId] INT NOT NULL PRIMARY KEY IDENTITY, 
	[CreationDate] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [Guid]        UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() UNIQUE,
    [Full] NVARCHAR(50) NULL, 
    [Short] NVARCHAR(5) NULL
)
