//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoCMS.News.Contract.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoCMS.News.Contract.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новостей на странице.
        /// </summary>
        public static string AdminNews_NewsOnPage {
            get {
                return ResourceManager.GetString("AdminNews_NewsOnPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новости.
        /// </summary>
        public static string AdminNews_PageTitle {
            get {
                return ResourceManager.GetString("AdminNews_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новость.
        /// </summary>
        public static string CreateNews_CreateButton {
            get {
                return ResourceManager.GetString("CreateNews_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание новости.
        /// </summary>
        public static string CreateNews_CreateTitle {
            get {
                return ResourceManager.GetString("CreateNews_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string CreateNews_Description {
            get {
                return ResourceManager.GetString("CreateNews_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование новости.
        /// </summary>
        public static string CreateNews_EditTitle {
            get {
                return ResourceManager.GetString("CreateNews_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string CreateNews_Image {
            get {
                return ResourceManager.GetString("CreateNews_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключевые слова.
        /// </summary>
        public static string CreateNews_Keywords {
            get {
                return ResourceManager.GetString("CreateNews_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время публикации.
        /// </summary>
        public static string CreateNews_PostingDateTime {
            get {
                return ResourceManager.GetString("CreateNews_PostingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Относительный URL.
        /// </summary>
        public static string CreateNews_RelativeUrl {
            get {
                return ResourceManager.GetString("CreateNews_RelativeUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст новости.
        /// </summary>
        public static string CreateNews_Text {
            get {
                return ResourceManager.GetString("CreateNews_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string CreateNews_Title {
            get {
                return ResourceManager.GetString("CreateNews_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К блогам.
        /// </summary>
        public static string EditBlog_ReturnToBlogs {
            get {
                return ResourceManager.GetString("EditBlog_ReturnToBlogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        public static string EditNews_AcceptButton {
            get {
                return ResourceManager.GetString("EditNews_AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К списку новостей.
        /// </summary>
        public static string EditNews_ReturnToNews {
            get {
                return ResourceManager.GetString("EditNews_ReturnToNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аннотация.
        /// </summary>
        public static string News_Annotation {
            get {
                return ResourceManager.GetString("News_Annotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        public static string News_Author {
            get {
                return ResourceManager.GetString("News_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новость.
        /// </summary>
        public static string News_CreateNews {
            get {
                return ResourceManager.GetString("News_CreateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string News_CreationDate {
            get {
                return ResourceManager.GetString("News_CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать&amp;nbsp;далее....
        /// </summary>
        public static string News_Cut {
            get {
                return ResourceManager.GetString("News_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string News_DeleteNews {
            get {
                return ResourceManager.GetString("News_DeleteNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string News_Description {
            get {
                return ResourceManager.GetString("News_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        public static string News_EditNews {
            get {
                return ResourceManager.GetString("News_EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключевые слова.
        /// </summary>
        public static string News_Keywords {
            get {
                return ResourceManager.GetString("News_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время публикации.
        /// </summary>
        public static string News_PostingDateTime {
            get {
                return ResourceManager.GetString("News_PostingDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать новость.
        /// </summary>
        public static string NewsView_EditNews {
            get {
                return ResourceManager.GetString("NewsView_EditNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Допустимы только буквы, цифры, символ почеркивания и дефис.
        /// </summary>
        public static string Validation_LettersNumbersUnderscoreDash {
            get {
                return ResourceManager.GetString("Validation_LettersNumbersUnderscoreDash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле обязательно для заполнения.
        /// </summary>
        public static string Validation_Reqiured {
            get {
                return ResourceManager.GetString("Validation_Reqiured", resourceCulture);
            }
        }
    }
}
