CREATE TABLE [News].[Tag]
(
	[TagId] INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	[CreationDate] DATETIME NOT NULL DEFAULT GETUTCDATE(),
	[Name] NVARCHAR(200) NOT NULL, 
    CONSTRAINT [AK_Tag_Name] UNIQUE ([Name]),
)
